<?xml version="1.0" encoding="UTF-8"?>
<crear>
    <{_paginaLogin_}>
        <nombre_formulario>Login</nombre_formulario>
        <tipo_de_servicio>{_tipoServicio_}</tipo_de_servicio>
        <motor_bd>{_tipoMotor_}</motor_bd>
        <tipo_formulario>autenticacion</tipo_formulario>
        <login>
            <que_quieres>Caja</que_quieres>
            <como_se_llama>Login</como_se_llama>
            <que_dato_recibira>texto</que_dato_recibira>
            <es_obligatorio>si</es_obligatorio>
        </login>
        <clave>
            <que_quieres>Caja</que_quieres>
            <como_se_llama>Clave</como_se_llama>
            <que_dato_recibira>clave</que_dato_recibira>
            <es_obligatorio>si</es_obligatorio>
        </clave>
    </{_paginaLogin_}>
</crear>
